name: Node CI

on: [push]

jobs:
 build:
  runs-on: NV
  env:
    DOTNET_NOLOGO: true
  steps:
    - uses: actions/checkout@main
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x' # SDK Version to use."
